spring:
  application:
    name: market-service

  datasource:
    url: jdbc:mysql://localhost:13306/marketdb?serverTimezone=Asia/Seoul
    username: root
    password: password1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 16379