spring:
  application:
    name: market-service

  profiles:
    include:
      - secret
      - storage

  datasource:
    url: jdbc:mysql://localhost:13306/marketdb?serverTimezone=Asia/Seoul
    username: root
    password: password1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
  data:
    redis:
      host: localhost
      port: 16379
    mongodb:
      uri: mongodb://admin:password1234@localhost:27017/marketdb?authSource=admin

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

jwt:
  secret: ${JWT_SECRET:vms60293845701234567890123456789012}
  access-expiration: 1800000    # 30분
  refresh-expiration: 604800000 # 7일