cloudflare:
  r2:
    endpoint: 'https://b2a412638ab7e26e02e5cdbaa2f84b8c.r2.cloudflarestorage.com'
    bucket: 'market-service'
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    public-url: 'https://pub-4a2d05f343134d04b22f1b727d23e326.r2.dev'
